stages:
  create-dataset:
    cmd: python scripts/create_dataset.py
    deps:
    - scripts/create_dataset.py
    outs:
    - assets/data
  extract-feature:
    cmd: python scripts/extract_features.py
    deps:
    - assets/data
    - scripts/extract_features.py
    outs:
    - assets/features
  train-model:
    cmd: python scripts/train_model.py
    deps:
    - assets/features/train_features.csv
    - assets/features/train_labels.csv
    outs:
    - assets/models
  eval-model:
    cmd: python scripts/eval_model.py
    deps:
    - assets/features/test_features.csv
    - assets/features/test_labels.csv
    - assets/models/model.pk
    - scripts/eval_model.py
    outs:
    - assets/metrics.json
